name: 'Hello World'
description: 'Greet someone'
inputs:
  url:
    description: 'RSS/ATOM url'
    required: true
  title-regex:
    description: 'Title Regex Match'
    required: true
  xpath-out-selector:
    description: 'XPath relative to selected `item`/`entry`'
    required: true
outputs:
  selection:
    description: "Selection based on XPath"
    value: ${{ steps.run.outputs.out }}
runs:
  using: "composite"
  steps:
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7'
    - id: build
      run: dotnet build ${GITHUB_ACTION_PATH}/TestAction.csproj -c Release
      shell: bash
    - id: run
      run: echo "out=$(dotnet run --project ${GITHUB_ACTION_PATH}/TestAction.csproj -c Release -- '${{ inputs.url }}' '${{ inputs.title-regex }}' '${{ inputs.xpath-out-selector }}')" >> $GITHUB_OUTPUT
      shell: bash
